fix: Set required config (to an empty value
Flask AppBuilder 5, for some reason, requires `RECAPTCHA_PUBLIC_KEY` to be set, or the UI cannot be used, and the following error is emitted on the container console:

```
  File "/stackable/app/lib64/python3.11/site-packages/superset/views/base.py", line 417, in cached_common_bootstrap_data
    frontend_config["RECAPTCHA_PUBLIC_KEY"] = app.config["RECAPTCHA_PUBLIC_KEY"]
                                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'RECAPTCHA_PUBLIC_KEY'
```